services:
  - type: web
    name: cypr-moviehub
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: JWT_SECRET
        generateValue: true
      - key: RESEND_API_KEY
        sync: false
    disk:
      name: cypr-sqlite-data
      mountPath: /app/server/data
      sizeGB: 1
